version: "2"

services:

  redmine:
    container_name: redmine
    build:
      context: ./redmine
      dockerfile: Dockerfile
    image: redmine
    depends_on:
      - mysql
    networks:
      - private-network
    ports:
      - "80:3000"
    environment:
      - TZ=Asia/Tokyo

  mysql:
    container_name: mysql
#    image: mysql:5.7
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: redmine_mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: redmine
#      MYSQL_USER: redmine
#      MYSQL_PASSWORD: redmine
    networks:
      - private-network
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Tokyo
#    restart: always
#    volumes:
#      - "./mysql:/etc/mysql/conf.d"
#    command: mysqld
#    command: bash -c "service mysql start && tail -f /dev/null"

networks:
  private-network:
    driver: bridge
