version: "3"

services:

  redmine_0_8_4:
    container_name: redmine_0_8_4
    hostname: redmine_0_8_4
    build:
      context: ./redmine/0.8.4
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    image: redmine:0.8.4
    depends_on:
      - redmine_mysql_5_6
    networks:
      - private-network
    ports:
      - "8084:3000"
    environment:
      - TZ=Asia/Tokyo

  redmine_1_2_0:
    container_name: redmine_1_2_0
    hostname: redmine_1_2_0
    build:
      context: ./redmine/1.2.0
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    image: redmine:1.2.0
    depends_on:
      - redmine_mysql_5_6
    networks:
      - private-network
    ports:
      - "8120:3000"
    environment:
      - TZ=Asia/Tokyo

  redmine_2_6_0:
    container_name: redmine_2_6_0
    hostname: redmine_2_6_0
    build:
      context: ./redmine/2.6.0
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    image: redmine:2.6.0
    depends_on:
      - redmine_mysql_5_6
    networks:
      - private-network
    ports:
      - "8260:3000"
    environment:
      - TZ=Asia/Tokyo

  redmine_3_4_0:
    container_name: redmine_3_4_0
    hostname: redmine_3_4_0
    build:
      context: ./redmine/3.4.0
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    image: redmine:3.4.0
    depends_on:
      - redmine_mysql_5_6
    networks:
      - private-network
    ports:
      - "8340:3000"
    environment:
      - TZ=Asia/Tokyo

  redmine_mysql_5_6:
    container_name: redmine_mysql_5_6
    hostname: redmine_mysql_5_6
    build:
      context: ./mysql
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    image: redmine_mysql_5_6
    networks:
      - private-network
    ports:
      - "33306:3306"
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - "./mysql:/etc/mysql/conf.d"

networks:
  private-network:
    driver: bridge
